Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.boot_timeout = 600

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "k0s-master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "k0s-worker"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 768
    end
  end
end
